name: make

on: workflow_dispatch

env:
  URL_BUSYBOX: https://busybox.net/downloads/busybox-1.32.0.tar.bz2
  URL_MINIZ: https://github.com/richgel999/miniz/releases/download/2.1.0/miniz-2.1.0.zip
  MAKEFLAGS: -j2

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: 2.0.5

      - uses: actions/checkout@v2

      - name: Build Native BusyBox
        run: make $MAKEFLAGS build/native/busybox URL_BUSYBOX=$URL_BUSYBOX URL_MINIZ=$URL_MINIZ

      - name: Build Wasm BusyBox
        run: make $MAKEFLAGS build/wasm/busybox_unstripped.js URL_BUSYBOX=$URL_BUSYBOX
